language: node_js
node_js:
- 8
- 10
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn lint
before_deploy:
- cd "./packages/@$(cut -d'@' -f2 <<<"$TRAVIS_TAG")"
deploy:
  provider: npm
  email: brendan@goodenough.nz
  api_key: "$NPM_TOKEN"
  on:
    tags: true
env:
  matrix:
    secure: IYYGgwCx0lKAeVpQermQXLLLNjHkd9sc1D3WqFA4mO9Elw60zETsd2jBYQoPOxP/zteyXPR0jvz1V5bYg8u2zBgPsrjZxOyVt5IS+sDTaLF5R3uZOSJDXYntIUsFhHhf5/+R2l3DLff41YfiGuOPQLJUn1tvFZFVMK3O6Zu7kH7wGyjq7QlTMn7ztfTZq9fZV4BmZy+P1vCmy8M/pET+CWNQcGmRg+tw52lyt/2673oKh1QvLhaWx/+SEFzWtrRpqdi9ryCBdy56kXZfCsOE/MoSQqGLep1AiZEVfKg/2dv55WQhqBU+jR6CLDGlhcGGEuUL3kgMFlC53LZ8KKeKOlL46zP04XJVsBEMRH3QJ0qhUDpC9131rA7YANApdR2MNpFSSiqyCSnrINSCGk9T3hOkazQHBn8Sedguz9GGMjP6w6N5maTdR4KQaOnWof/AQohY2W7MT7/GEv6k9w8GunrHCLZ/5OYS9ddo6/W7UF0IHId9G5Mpr8Mi/VehEgY81iqX+EtcXrj7AWsqver3fPDghtHhq+NRJqqCHkRQEa4YQ/k3/vz7DHw2VUl/SuLDJ34SB3Cn7aSHbYFfTT+6GG3rb7E7BzNnKuOZIPHz+u2bKoPjaD8sl3VtOCGgtC2jQHK/Eb9m6iHtRJXJYjL3SRQ4KYS8s01sIvt12qJpaTs=
