language: node_js
node_js:
- 8
- 9
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: script
  script: bash scripts/ci/deploy.sh
  on:
    branch: dev
env:
  secure: iyd5ckQxXgIaDVcxF2I66yVJBBRTR82qzLnqUf7+9MC2wt19VjaqCey8u6aTDMU27AkhQ9T9D/wrcZKOu8AxFsAdKnpeWr7UacSoA9sjK0GgeNSsk1t0gZypL8jhaAJVONIcuUWQ3e606j5ncCMc2DEgeb1LYtnu8cuTDTn8DXljVo7xEds1mYbP9KK/sHZJzVbHy5oH+TxkBdQnCeGBwjVRLjn1R2omNptuBwKpy2nCbpnmF0uI7c7qlJBCLgzjpymsWONVy81WCDeIsQMim/0j2mydOYevuerr3z5tFCctegEZc2I/dAghLMahQC7iJMDUr383Dl84DlwqToAKU0/SY17WUISF1VIfhh8q1KLxLWZ/heZKWMPdmwR2/YVIo93W0o6rpRqBRTl4h6oKn8ouQHc5R4oZogeQJOnZHn8nIDHVpMKIJKa/FDPVSPUVYR5B558d9EdOT2FeoSrURX4MSpCI/OXNZaBKHXjRN597ip116jlnLr3bLRwHuMFPFyFC9BWj2NxbRC233RxI4gFi3PCXvwyA59IKwTFmF3AQJijm1kZL075FWvkVgPmKJ/XqSz7Dy2yCGnjhqfOIvTu1TifmufmOu9yUvxW7pTuxtEY2r+HMBWO+sj47ToOckBSb1KCx4E/Si2MtLaKjl1S3KDYVuO0xu7/Ssmgh71M=
